#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
# Putting image is optional, but using this as an example how to run on Graviton
image:
  repository: kong/kong-gateway
  tag: "3.4.0.0-rhel"
proxy:
  enabled: true
  type: LoadBalancer
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Type=proxy"
    external-dns.alpha.kubernetes.io/hostname: "proxy.kong-dp.internal"

resources:
  limits:
    cpu: 1200m
    memory: 800Mi
  requests:
    cpu: 300m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

