#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
# Putting image is optional, but using this as an example how to run on Graviton
image:
  repository: kong/kong-gateway
proxy:
  enabled: true
  type: NodePort
  tls:
    enabled: false
  ingress:
    # Enable/disable exposure using ingress.
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/load-balancer-name: alb-kong-proxy
      alb.ingress.kubernetes.io/success-codes: '404' # TODO : THIS IS A WORKAROUND.
      alb.ingress.kubernetes.io/target-type: ip


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75