#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
proxy:
  enabled: true
  type: LoadBalancer
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Type=proxy"
    external-dns.alpha.kubernetes.io/hostname: "proxy.kong-dp.internal"

env:
  ssl_cert: "/etc/secrets/${acm_pca_cert_secretname}/tls.crt"
  ssl_cert_key: "/etc/secrets/${acm_pca_cert_secretname}/tls.key"

secretVolumes:
- "${acm_pca_cert_secretname}"


resources:
  limits:
    cpu: 1200m
    memory: 800Mi
  requests:
    cpu: 300m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

